## Midway Project

In [76]:
import pandas as pd
import numpy as np

In [41]:
py_df = pd.read_csv("../data/2020_sharing_data_outside.csv", 
                    low_memory= False,
                    )
py_df.head(2)

,is.python.main,other.lang.None,other.lang.Java,other.lang.JavaScript,other.lang.C/C++,other.lang.PHP,other.lang.C#,other.lang.Ruby,other.lang.Bash / Shell,other.lang.Objective-C,other.lang.Go,other.lang.Visual Basic,other.lang.Scala,other.lang.SQL,other.lang.Kotlin,other.lang.R,other.lang.Swift,other.lang.Clojure,other.lang.Perl,other.lang.Rust,other.lang.Groovy,other.lang.TypeScript,other.lang.CoffeeScript,other.lang.HTML/CSS,other.lang.Other,python.years,years.of.coding,main.purposes,other.purposes.Educational purposes,other.purposes.Data analysis,other.purposes.DevOps / System administration / Writing automation scripts,other.purposes.Software testing / Writing automated tests,other.purposes.Software prototyping,other.purposes.Web development,other.purposes.Machine learning,other.purposes.Mobile development,other.purposes.Desktop development,other.purposes.Computer graphics,other.purposes.Network programming,other.purposes.Game development,other.purposes.Multimedia applications development,other.purposes.Embedded development,other.purposes.Programming of web parsers / scrapers / crawlers,other.purposes.Other,how.involved.Computer graphics,how.involved.Data analysis,how.involved.DevOps / System administration / Writing automation scripts,how.involved.Educational purposes,how.involved.Software testing / Writing automated tests,how.involved.Web development,how.involved.Network programming,how.involved.Desktop development,how.involved.Machine learning,how.involved.Software prototyping,how.involved.Programming of web parsers / scrapers / crawlers,how.involved.Embedded development,how.involved.Mobile development,how.involved.Game development,how.involved.Multimedia applications development,use.python.most,are.you.datascientist,python.version.most,python2.version.most,python3.version.most,python.version.upgrade.I donâ€™t update,python.version.upgrade.Somebody else manages Python updates for me,python.version.upgrade.Python_org,python.version.upgrade.Build from source,python.version.upgrade.Automatic upgrade via cloud provider,python.version.upgrade.Anaconda,python.version.upgrade.ActivePython,python.version.upgrade.Intel Distribution for Python,"python.version.upgrade.OS-provided Python (via apt-get, yum, homebrew, etc_)",python.version.upgrade.pyenv,python.version.upgrade.pythonz,python.version.upgrade.I use Docker containers,python.version.upgrade.Other,isolate.environments.None,isolate.environments.Virtualenv,isolate.environments.Pipenv,isolate.environments.Poetry,isolate.environments.Conda,isolate.environments.Docker,isolate.environments.Vagrant / virtual machines,isolate.environments.Other,web.frameworks.None,web.frameworks.Django,web.frameworks.web2py,web.frameworks.Bottle,web.frameworks.CherryPy,web.frameworks.Flask,web.frameworks.Hug,web.frameworks.Pyramid,web.frameworks.Tornado,web.frameworks.Falcon,web.frameworks.FastAPI,web.frameworks.Other,data.frameworks.None,data.frameworks.PyTorch,data.frameworks.NumPy,data.frameworks.SciPy,data.frameworks.Pandas,data.frameworks.Matplotlib,data.frameworks.Seaborn,data.frameworks.SciKit-Learn,data.frameworks.Keras,data.frameworks.TensorFlow,data.frameworks.Theano,data.frameworks.NLTK,data.frameworks.MXNet,data.frameworks.Gensim,data.frameworks.Other,other.frameworks.None,other.frameworks.Requests,other.frameworks.aiohttp,other.frameworks.PyQT,other.frameworks.PyGTK,other.frameworks.wxPython,other.frameworks.Pillow,other.frameworks.Tkinter,other.frameworks.Pygame,other.frameworks.Twisted,other.frameworks.Asyncio,other.frameworks.Kivy,other.frameworks.Six,other.frameworks.Scrapy,other.frameworks.Other,cloud.platform.None,cloud.platform.Google Cloud Platform,cloud.platform.AWS,cloud.platform.Microsoft Azure,cloud.platform.Rackspace,cloud.platform.Heroku,cloud.platform.DigitalOcean,cloud.platform.Linode,cloud.platform.PythonAnywhere,cloud.platform.OpenShift,cloud.platform.OpenStack,cloud.platform.Other,run.in.cloud.None of the following,run.in.cloud.In virtual machines,run.in.cloud.Within containers,run.in.cloud.On a Platform-as-a-Service (such as Heroku or Google App Engine),run.in.cloud.Serverless (such as AWS Lambda or Cloud Functions),run.in.cloud.Other,develop.for.cloud.None of the following,develop.for.cloud.With local system interpreter,develop.for.cloud.Locally with virtualenv (or similar),develop.for.cloud.In Docker containers,develop.for.cloud.In virtual machines,develop.for.cloud.In remote development environments,develop.for.cloud.Directly in the production environment,develop.for.cloud.Other,devenv.os.Windows,devenv.os.Linux,devenv.os.macOS,devenv.os.BSD,devenv.os.Other,unittesting.None,unittesting.pytest,unittesting.nose,unittesting.unittest,unittesting.doctest,unittesting.Tox,unittesting.Hypothesis,unittesting.mock,unittesting.Other,orm.No database development,orm.Raw SQL,orm.Django ORM,orm.SQLAlchemy,orm.Peewee,orm.Dejavu,orm.PonyORM,orm.SQLObject,orm.Tortoise ORM,orm.Other,database.None,database.DB2,database.MS SQL Server,database.MySQL,database.Oracle Database,database.PostgreSQL,database.SQLite,database.Cassandra,database.Couchbase,database.HBase,database.MongoDB,database.Neo4j,database.Redis,database.Amazon Redshift,database.h2,database.Other,bigdata.None,bigdata.Apache Beam,bigdata.Apache Flink,bigdata.Apache Hadoop/MapReduce,bigdata.Apache Hive,bigdata.Apache Samza,bigdata.Apache Kafka,bigdata.Apache Spark,bigdata.Apache Tez,bigdata.Dask,bigdata.ClickHouse,bigdata.Other,ci.None,ci.Jenkins / Hudson,ci.TeamCity,ci.Bamboo,ci.Travis CI,ci.CircleCI,ci.CruiseControl,ci.Gitlab CI,ci.AppVeyor,ci.Other,configuration.management.None,configuration.management.Salt,configuration.management.Puppet,configuration.management.Chef,configuration.management.Ansible,configuration.management.Custom solution,configuration.management.Other,ide.main,ide.editor.None,ide.editor.Other,ide.editor.PyCharm Professional Edition,ide.editor.PyCharm Community Edition,ide.editor.Sublime Text,ide.editor.Vim,ide.editor.Atom,ide.editor.VS Code,ide.editor.Eclipse + Pydev,ide.editor.JupyterLab,ide.editor.Jupyter Notebook,ide.editor.IntelliJ IDEA,ide.editor.NotePad++,ide.editor.IDLE,ide.editor.Emacs,ide.editor.Python Tools for Visual Studio (PTVS),ide.editor.Spyder,several.projects,first.learn.about.main.ide,how.often.use.main.ide,missing.features.main.ide,nps.main.ide,job.team,team.size,employment.status,company.size,job.role.DBA,job.role.Architect,job.role.QA engineer,job.role.Developer / Programmer,job.role.Technical writer,job.role.Technical support,job.role.Data analyst,job.role.Business analyst,job.role.Team lead,job.role.Product manager,job.role.CIO / CEO / CTO,job.role.Systems analyst,job.role.Other,age,country.live
0,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash / Shell,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3â€“5 years,1â€“2 years,For work,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Computer graphics,NaN,NaN,NaN,NaN,NaN,NaN,Computer graphics,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Python 3,NaN,Python 3_7,NaN,NaN,Python_org,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Poetry,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CherryPy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Matplotlib,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,aiohttp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AWS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Within containers,NaN,NaN,NaN,NaN,With local system interpreter,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Linux,NaN,NaN,NaN,NaN,pytest,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Django ORM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MongoDB,NaN,NaN,NaN,NaN,NaN,NaN,Apache Beam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CircleCI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ansible,NaN,NaN,PyCharm Community Edition,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Emacs,NaN,NaN,"Yes, I work on many different projects",Conference / User Group,Weekly,"No, it has all the features I need",3.00,Work as an external consultant or trainer,NaN,Partially employed by a company / organization,Just me,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Business analyst,NaN,NaN,NaN,NaN,NaN,30â€“39,NaN
1,Yes,NaN,Java,JavaScript,NaN,NaN,C#,NaN,NaN,NaN,NaN,NaN,NaN,SQL,NaN,R,NaN,NaN,NaN,NaN,NaN,TypeScript,NaN,NaN,NaN,3â€“5 years,3â€“5 years,Both for work and personal,Educational purposes,NaN,NaN,Software testing / Writing automated tests,Software prototyping,NaN,Machine learning,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Programming of web parsers / scrapers / crawlers,NaN,NaN,NaN,NaN,Educational purposes,Software testing / Writing automated tests,NaN,NaN,NaN,Machine learning,Software prototyping,Programming of web parsers / scrapers / crawlers,NaN,NaN,NaN,NaN,Software prototyping,Yes,Python 3,NaN,Python 3_6,NaN,NaN,NaN,NaN,Automatic upgrade via cloud provider,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Conda,Docker,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tornado,NaN,NaN,NaN,NaN,PyTorch,NumPy,SciPy,Pandas,NaN,NaN,SciKit-Learn,NaN,TensorFlow,NaN,NLTK,NaN,NaN,NaN,NaN,Requests,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Six,Scrapy,NaN,NaN,Google Cloud Platform,AWS,Microsoft Azure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,In virtual machines,Within containers,NaN,Serverless (such as AWS Lambda or Cloud Functi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Directly in the production environment,NaN,Windows,NaN,NaN,NaN,NaN,NaN,NaN,NaN,unittest,NaN,NaN,NaN,mock,NaN,No database development,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MySQL,NaN,PostgreSQL,SQLite,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,VS Code,NaN,NaN,NaN,NaN,Sublime Text,NaN,NaN,NaN,NaN,NaN,Jupyter Notebook,NaN,NotePad++,NaN,NaN,NaN,NaN,"Yes, I work on one main and several side projects",School / University,Daily,"No, it has all the features I need",8.00,Work in a team,2-7 people,Fully employed by a company / organization,"More than 5,000",NaN,NaN,NaN,Developer / Programmer,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21â€“29,India

In [42]:
pd.set_option('display.max_rows', 50)
pd.set_option('display.max_columns', None)
pd.options.display.float_format = '{:,.2f}'.format

In [43]:
general_columns = ['age',
                   'are.you.datascientist',
                   'is.python.main',
                   'company.size',
                   'country.live',
                   'employment.status',
                   'first.learn.about.main.ide',
                   'how.often.use.main.ide',
                   'is.python.main',
                   'main.purposes'
                   'missing.features.main.ide'
                   'nps.main.ide',
                   'python.version.most',
                   'python.years',
                   'python2.version.most',
                   'python3.version.most',
                   'several.projects',
                   'team.size',
                   'use.python.most',
                   'years.of.coding'
                    ]

In [44]:
def column_multi_name(column_name):
    if column_name in general_columns:
        return ('general', column_name)
    else:
        first, rest = column_name.rsplit('.',1)
        return (first, rest)

In [45]:
py_df.columns = (
    pd
    .MultiIndex.from_tuples([
        column_multi_name(one_column_name)
        for one_column_name in py_df.columns
    ])
)

In [46]:
py_df.head(2)

         general other.lang                                         \
  is.python.main       None  Java  JavaScript C/C++  PHP   C# Ruby
0            Yes        NaN   NaN         NaN   NaN  NaN  NaN  NaN
1            Yes        NaN  Java  JavaScript   NaN  NaN   C#  NaN

                                                                            \
   Bash / Shell Objective-C   Go Visual Basic Scala  SQL Kotlin    R Swift
0  Bash / Shell         NaN  NaN          NaN   NaN  NaN    NaN  NaN   NaN
1           NaN         NaN  NaN          NaN   NaN  SQL    NaN    R   NaN

                                                                    \
  Clojure Perl Rust Groovy  TypeScript CoffeeScript HTML/CSS Other
0     NaN  NaN  NaN    NaN         NaN          NaN      NaN   NaN
1     NaN  NaN  NaN    NaN  TypeScript          NaN      NaN   NaN

       general                                        main  \
  python.years years.of.coding                    purposes
0    3â€“5 years       1â€“2 years                    For work
1    3â€“5 years       3â€“5 years  Both for work and personal

         other.purposes                \
   Educational purposes Data analysis
0                   NaN           NaN
1  Educational purposes           NaN

                                                               \
  DevOps / System administration / Writing automation scripts
0                                                NaN
1                                                NaN

                                                                     \
   Software testing / Writing automated tests  Software prototyping
0                                         NaN                   NaN
1  Software testing / Writing automated tests  Software prototyping

                                                                            \
  Web development  Machine learning Mobile development Desktop development
0             NaN               NaN                NaN                 NaN
1             NaN  Machine learning                NaN                 NaN

                                                           \
   Computer graphics Network programming Game development
0  Computer graphics                 NaN              NaN
1                NaN                 NaN              NaN

                                                            \
  Multimedia applications development Embedded development
0                                 NaN                  NaN
1                                 NaN                  NaN

                                                                how.involved  \
   Programming of web parsers / scrapers / crawlers Other  Computer graphics
0                                               NaN   NaN  Computer graphics
1  Programming of web parsers / scrapers / crawlers   NaN                NaN

                                                                             \
  Data analysis DevOps / System administration / Writing automation scripts
0           NaN                                                NaN
1           NaN                                                NaN

                                                                     \
   Educational purposes  Software testing / Writing automated tests
0                   NaN                                         NaN
1  Educational purposes  Software testing / Writing automated tests

                                                                             \
  Web development Network programming Desktop development  Machine learning
0             NaN                 NaN                 NaN               NaN
1             NaN                 NaN                 NaN  Machine learning

                                                                           \
   Software prototyping  Programming of web parsers / scrapers / crawlers
0                   NaN                                               NaN
1  Software prototyping  Programming of web parsers / scrapers / crawlers

                                                            \
  Embedded development Mobile development Game development
0                  NaN                NaN              NaN
1                  NaN                NaN              NaN

                                                    general  \
  Multimedia applications development       use.python.most
0                                 NaN                   NaN
1                                 NaN  Software prototyping

                                                                  \
  are.you.datascientist python.version.most python2.version.most
0                   NaN            Python 3                  NaN
1                   Yes            Python 3                  NaN

                       python.version.upgrade  \
  python3.version.most         I donâ€™t update
0           Python 3_7                    NaN
1           Python 3_6                    NaN

                                                                             \
  Somebody else manages Python updates for me  Python_org Build from source
0                                         NaN  Python_org               NaN
1                                         NaN         NaN               NaN

                                                               \
   Automatic upgrade via cloud provider Anaconda ActivePython
0                                   NaN      NaN          NaN
1  Automatic upgrade via cloud provider      NaN          NaN

                                 \
  Intel Distribution for Python
0                           NaN
1                           NaN

                                                                       \
  OS-provided Python (via apt-get, yum, homebrew, etc_) pyenv pythonz
0                                                NaN      NaN     NaN
1                                                NaN      NaN     NaN

                                isolate.environments                    \
  I use Docker containers Other                 None Virtualenv Pipenv
0                     NaN   NaN                  NaN        NaN    NaN
1                     NaN   NaN                  NaN        NaN    NaN

                                                           web.frameworks  \
   Poetry  Conda  Docker Vagrant  / virtual machines Other           None
0  Poetry    NaN     NaN                         NaN   NaN            NaN
1     NaN  Conda  Docker                         NaN   NaN            NaN

                                                                        \
  Django web2py Bottle  CherryPyÂ  FlaskÂ   Hug PyramidÂ   Tornado Falcon
0    NaN    NaN    NaN  CherryPyÂ     NaN  NaN      NaN      NaN    NaN
1    NaN    NaN    NaN        NaN    NaN  NaN      NaN  Tornado    NaN

                data.frameworks                                             \
  FastAPI Other            None  PyTorch  NumPy  SciPy  Pandas  Matplotlib
0     NaN   NaN             NaN      NaN    NaN    NaN     NaN  Matplotlib
1     NaN   NaN             NaN  PyTorch  NumPy  SciPy  Pandas         NaN

                                                                           \
  Seaborn  SciKit-Learn Keras  TensorFlow Theano  NLTK MXNet Gensim Other
0     NaN           NaN   NaN         NaN    NaN   NaN   NaN    NaN   NaN
1     NaN  SciKit-Learn   NaN  TensorFlow    NaN  NLTK   NaN    NaN   NaN

  other.frameworks                                                        \
              None  Requests  aiohttp PyQT PyGTK wxPython Pillow Tkinter
0              NaN       NaN  aiohttp  NaN   NaN      NaN    NaN     NaN
1              NaN  Requests      NaN  NaN   NaN      NaN    NaN     NaN

                                                 cloud.platform  \
  Pygame Twisted Asyncio Kivy  Six  Scrapy Other           None
0    NaN     NaN     NaN  NaN  NaN     NaN   NaN            NaN
1    NaN     NaN     NaN  NaN  Six  Scrapy   NaN            NaN

                                                                              \
   Google Cloud Platform  AWS  Microsoft Azure Rackspace Heroku DigitalOcean
0                    NaN  AWS              NaN       NaN    NaN          NaN
1  Google Cloud Platform  AWS  Microsoft Azure       NaN    NaN          NaN

                                                           run.in.cloud  \
  Linode PythonAnywhere OpenShift OpenStack Other None of the following
0    NaN            NaN       NaN       NaN   NaN                   NaN
1    NaN            NaN       NaN       NaN   NaN                   NaN

                                           \
   In virtual machines  Within containers
0                  NaN  Within containers
1  In virtual machines  Within containers

                                                                    \
  On a Platform-as-a-Service (such as Heroku or Google App Engine)
0                                                NaN
1                                                NaN

                                                            \
  Serverless (such as AWS Lambda or Cloud Functions) Other
0                                                NaN   NaN
1  Serverless (such as AWS Lambda or Cloud Functi...   NaN

      develop.for.cloud                                 \
  None of the following  With local system interpreter
0                   NaN  With local system interpreter
1                   NaN                            NaN

                                                             \
  Locally with virtualenv (or similar) In Docker containers
0                                  NaN                  NaN
1                                  NaN                  NaN

                                                          \
  In virtual machines In remote development environments
0                 NaN                                NaN
1                 NaN                                NaN

                                                devenv.os                    \
   Directly in the production environment Other   Windows  Linux macOS  BSD
0                                     NaN   NaN       NaN  Linux   NaN  NaN
1  Directly in the production environment   NaN   Windows    NaN   NaN  NaN

        unittesting                                                       \
  Other        None  pytest nose  unittest doctest  Tox Hypothesis  mock
0   NaN         NaN  pytest  NaN       NaN     NaN  NaN        NaN   NaN
1   NaN         NaN     NaN  NaN  unittest     NaN  NaN        NaN  mock

                             orm                                               \
  Other  No database development Raw SQL  Django ORM SQLAlchemy Peewee Dejavu
0   NaN                      NaN     NaN  Django ORM        NaN    NaN    NaN
1   NaN  No database development     NaN         NaN        NaN    NaN    NaN

                                       database                            \
  PonyORM SQLObject Tortoise ORM Other     None  DB2 MS SQL Server  MySQL
0     NaN       NaN          NaN   NaN      NaN  NaN           NaN    NaN
1     NaN       NaN          NaN   NaN      NaN  NaN           NaN  MySQL

                                                                          \
  Oracle Database  PostgreSQL  SQLite Cassandra Couchbase HBase  MongoDB
0             NaN         NaN     NaN       NaN       NaN   NaN  MongoDB
1             NaN  PostgreSQL  SQLite       NaN       NaN   NaN      NaN

                                         bigdata                            \
  Neo4j Redis Amazon Redshift   h2 Other    None  Apache Beam Apache Flink
0   NaN   NaN             NaN  NaN   NaN     NaN  Apache Beam          NaN
1   NaN   NaN             NaN  NaN   NaN     NaN          NaN          NaN

                                                                              \
  Apache Hadoop/MapReduce Apache Hive Apache Samza Apache Kafka Apache Spark
0                     NaN         NaN          NaN          NaN          NaN
1                     NaN         NaN          NaN          NaN          NaN

                                     ci                                   \
  Apache Tez Dask ClickHouse Other None Jenkins / Hudson TeamCity Bamboo
0        NaN  NaN        NaN   NaN  NaN              NaN      NaN    NaN
1        NaN  NaN        NaN   NaN  NaN              NaN      NaN    NaN

                                                              \
  Travis CI  CircleCI CruiseControl Gitlab CI AppVeyor Other
0       NaN  CircleCI           NaN       NaN      NaN   NaN
1       NaN       NaN           NaN       NaN      NaN   NaN

  configuration.management                                                  \
                      None Salt Puppet Chef  Ansible Custom solution Other
0                      NaN  NaN    NaN  NaN  Ansible             NaN   NaN
1                      NaN  NaN    NaN  NaN      NaN             NaN   NaN

                         ide ide.editor                                     \
                        main       None Other PyCharm Professional Edition
0  PyCharm Community Edition        NaN   NaN                          NaN
1                    VS Code        NaN   NaN                          NaN

                                                                             \
  PyCharm Community Edition  Sublime Text  Vim Atom VS Code Eclipse + Pydev
0                       NaN           NaN  NaN  NaN     NaN             NaN
1                       NaN  Sublime Text  NaN  NaN     NaN             NaN

                                                                     \
  JupyterLab  Jupyter Notebook IntelliJ IDEA  NotePad++ IDLE  Emacs
0        NaN               NaN           NaN        NaN  NaN  Emacs
1        NaN  Jupyter Notebook           NaN  NotePad++  NaN    NaN

                                                \
  Python Tools for Visual Studio (PTVS) Spyder
0                                   NaN    NaN
1                                   NaN    NaN

                                             general  \
                                    several.projects
0             Yes, I work on many different projects
1  Yes, I work on one main and several side projects

                                                     \
  first.learn.about.main.ide how.often.use.main.ide
0    Conference / User Group                 Weekly
1        School / University                  Daily

                missing.features.main nps.main  \
                                  ide      ide
0  No, it has all the features I need     3.00
1  No, it has all the features I need     8.00

                                         job     general  \
                                        team   team.size
0  Work as an external consultant or trainer         NaN
1                             Work in a team  2-7 people

                                                                   job.role  \
                                employment.status     company.size      DBA
0  Partially employed by a company / organization          Just me      NaN
1      Fully employed by a company / organization  More than 5,000      NaN

                                                                  \
  Architect QA engineer  Developer / Programmer Technical writer
0       NaN         NaN                     NaN              NaN
1       NaN         NaN  Developer / Programmer              NaN

                                                                              \
  Technical support Data analyst  Business analyst Team lead Product manager
0               NaN          NaN  Business analyst       NaN             NaN
1               NaN          NaN               NaN       NaN             NaN

                                        general
  CIO / CEO / CTO Systems analyst Other     age country.live
0             NaN             NaN   NaN   30â€“39          NaN
1             NaN             NaN   NaN   21â€“29        India

In [47]:
# sorting columns
py_df = py_df[sorted(py_df.columns)]
py_df.head(2)

       bigdata                                                                \
   Apache Beam Apache Flink Apache Hadoop/MapReduce Apache Hive Apache Kafka
0  Apache Beam          NaN                     NaN         NaN          NaN
1          NaN          NaN                     NaN         NaN          NaN

                                                                        ci  \
  Apache Samza Apache Spark Apache Tez ClickHouse Dask None Other AppVeyor
0          NaN          NaN        NaN        NaN  NaN  NaN   NaN      NaN
1          NaN          NaN        NaN        NaN  NaN  NaN   NaN      NaN

                                                                        \
  Bamboo  CircleCI CruiseControl Gitlab CI Jenkins / Hudson None Other
0    NaN  CircleCI           NaN       NaN              NaN  NaN   NaN
1    NaN       NaN           NaN       NaN              NaN  NaN   NaN

                     cloud.platform                                      \
  TeamCity Travis CI            AWS DigitalOcean  Google Cloud Platform
0      NaN       NaN            AWS          NaN                    NaN
1      NaN       NaN            AWS          NaN  Google Cloud Platform

                                                                 \
  Heroku Linode  Microsoft Azure None OpenShift OpenStack Other
0    NaN    NaN              NaN  NaN       NaN       NaN   NaN
1    NaN    NaN  Microsoft Azure  NaN       NaN       NaN   NaN

                           configuration.management                            \
  PythonAnywhere Rackspace                  Ansible Chef Custom solution None
0            NaN       NaN                  Ansible  NaN             NaN  NaN
1            NaN       NaN                      NaN  NaN             NaN  NaN

                    data.frameworks                                            \
  Other Puppet Salt          Gensim Keras MXNet  Matplotlib  NLTK None  NumPy
0   NaN    NaN  NaN             NaN   NaN   NaN  Matplotlib   NaN  NaN    NaN
1   NaN    NaN  NaN             NaN   NaN   NaN         NaN  NLTK  NaN  NumPy

                                                                          \
  Other  Pandas  PyTorch  SciKit-Learn  SciPy Seaborn  TensorFlow Theano
0   NaN     NaN      NaN           NaN    NaN     NaN         NaN    NaN
1   NaN  Pandas  PyTorch  SciKit-Learn  SciPy     NaN  TensorFlow    NaN

         database                                                        \
  Amazon Redshift Cassandra Couchbase  DB2 HBase MS SQL Server  MongoDB
0             NaN       NaN       NaN  NaN   NaN           NaN  MongoDB
1             NaN       NaN       NaN  NaN   NaN           NaN      NaN

                                                                          \
   MySQL Neo4j None Oracle Database Other  PostgreSQL Redis  SQLite   h2
0    NaN   NaN  NaN             NaN   NaN         NaN   NaN     NaN  NaN
1  MySQL   NaN  NaN             NaN   NaN  PostgreSQL   NaN  SQLite  NaN

                        develop.for.cloud                       \
   Directly in the production environment In Docker containers
0                                     NaN                  NaN
1  Directly in the production environment                  NaN

                                                          \
  In remote development environments In virtual machines
0                                NaN                 NaN
1                                NaN                 NaN

                                                                    \
  Locally with virtualenv (or similar) None of the following Other
0                                  NaN                   NaN   NaN
1                                  NaN                   NaN   NaN

                                 devenv.os                              \
   With local system interpreter       BSD  Linux Other  Windows macOS
0  With local system interpreter       NaN  Linux   NaN      NaN   NaN
1                            NaN       NaN    NaN   NaN  Windows   NaN

  general                                                      \
      age are.you.datascientist     company.size country.live
0   30â€“39                   NaN          Just me          NaN
1   21â€“29                   Yes  More than 5,000        India

                                                                              \
                                employment.status first.learn.about.main.ide
0  Partially employed by a company / organization    Conference / User Group
1      Fully employed by a company / organization        School / University

                                                                          \
  how.often.use.main.ide is.python.main python.version.most python.years
0                 Weekly            Yes            Python 3    3â€“5 years
1                  Daily            Yes            Python 3    3â€“5 years

                                             \
  python2.version.most python3.version.most
0                  NaN           Python 3_7
1                  NaN           Python 3_6

                                                                  \
                                    several.projects   team.size
0             Yes, I work on many different projects         NaN
1  Yes, I work on one main and several side projects  2-7 people

                                              how.involved                \
        use.python.most years.of.coding  Computer graphics Data analysis
0                   NaN       1â€“2 years  Computer graphics           NaN
1  Software prototyping       3â€“5 years                NaN           NaN

                       \
  Desktop development
0                 NaN
1                 NaN

                                                               \
  DevOps / System administration / Writing automation scripts
0                                                NaN
1                                                NaN

                                                               \
   Educational purposes Embedded development Game development
0                   NaN                  NaN              NaN
1  Educational purposes                  NaN              NaN

                                                                            \
   Machine learning Mobile development Multimedia applications development
0               NaN                NaN                                 NaN
1  Machine learning                NaN                                 NaN

                                                                         \
  Network programming  Programming of web parsers / scrapers / crawlers
0                 NaN                                               NaN
1                 NaN  Programming of web parsers / scrapers / crawlers

                                                                     \
   Software prototyping  Software testing / Writing automated tests
0                   NaN                                         NaN
1  Software prototyping  Software testing / Writing automated tests

                                         ide ide.editor                  \
  Web development                       main       Atom Eclipse + Pydev
0             NaN  PyCharm Community Edition        NaN             NaN
1             NaN                    VS Code        NaN             NaN

                                                                          \
   Emacs IDLE IntelliJ IDEA  Jupyter Notebook JupyterLab None  NotePad++
0  Emacs  NaN           NaN               NaN        NaN  NaN        NaN
1    NaN  NaN           NaN  Jupyter Notebook        NaN  NaN  NotePad++

                                                                \
  Other PyCharm Community Edition PyCharm Professional Edition
0   NaN                       NaN                          NaN
1   NaN                       NaN                          NaN

                                                                           \
  Python Tools for Visual Studio (PTVS) Spyder  Sublime Text VS Code  Vim
0                                   NaN    NaN           NaN     NaN  NaN
1                                   NaN    NaN  Sublime Text     NaN  NaN

  isolate.environments                                    \
                 Conda  Docker None Other Pipenv  Poetry
0                  NaN     NaN  NaN   NaN    NaN  Poetry
1                Conda  Docker  NaN   NaN    NaN     NaN

                                          \
  Vagrant  / virtual machines Virtualenv
0                         NaN        NaN
1                         NaN        NaN

                                         job  job.role                    \
                                        team Architect  Business analyst
0  Work as an external consultant or trainer       NaN  Business analyst
1                             Work in a team       NaN               NaN

                                                                   \
  CIO / CEO / CTO  DBA Data analyst  Developer / Programmer Other
0             NaN  NaN          NaN                     NaN   NaN
1             NaN  NaN          NaN  Developer / Programmer   NaN

                                                                           \
  Product manager QA engineer Systems analyst Team lead Technical support
0             NaN         NaN             NaN       NaN               NaN
1             NaN         NaN             NaN       NaN               NaN

                                          main  \
  Technical writer                    purposes
0              NaN                    For work
1              NaN  Both for work and personal

                missing.features.main nps.main    orm              \
                                  ide      ide Dejavu  Django ORM
0  No, it has all the features I need     3.00    NaN  Django ORM
1  No, it has all the features I need     8.00    NaN         NaN

                                                                              \
   No database development Other Peewee PonyORM Raw SQL SQLAlchemy SQLObject
0                      NaN   NaN    NaN     NaN     NaN        NaN       NaN
1  No database development   NaN    NaN     NaN     NaN        NaN       NaN

               other.frameworks                                           \
  Tortoise ORM          Asyncio Kivy None Other Pillow PyGTK PyQT Pygame
0          NaN              NaN  NaN  NaN   NaN    NaN   NaN  NaN    NaN
1          NaN              NaN  NaN  NaN   NaN    NaN   NaN  NaN    NaN

                                                              other.lang       \
   Requests  Scrapy  Six Tkinter Twisted  aiohttp wxPython  Bash / Shell   C#
0       NaN     NaN  NaN     NaN     NaN  aiohttp      NaN  Bash / Shell  NaN
1  Requests  Scrapy  Six     NaN     NaN      NaN      NaN           NaN   C#

                                                                            \
  C/C++ Clojure CoffeeScript   Go Groovy HTML/CSS  Java  JavaScript Kotlin
0   NaN     NaN          NaN  NaN    NaN      NaN   NaN         NaN    NaN
1   NaN     NaN          NaN  NaN    NaN      NaN  Java  JavaScript    NaN

                                                                    \
  None Objective-C Other  PHP Perl    R Ruby Rust  SQL Scala Swift
0  NaN         NaN   NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN   NaN
1  NaN         NaN   NaN  NaN  NaN    R  NaN  NaN  SQL   NaN   NaN

                               other.purposes                \
   TypeScript Visual Basic  Computer graphics Data analysis
0         NaN          NaN  Computer graphics           NaN
1  TypeScript          NaN                NaN           NaN

                       \
  Desktop development
0                 NaN
1                 NaN

                                                               \
  DevOps / System administration / Writing automation scripts
0                                                NaN
1                                                NaN

                                                               \
   Educational purposes Embedded development Game development
0                   NaN                  NaN              NaN
1  Educational purposes                  NaN              NaN

                                                                            \
   Machine learning Mobile development Multimedia applications development
0               NaN                NaN                                 NaN
1  Machine learning                NaN                                 NaN

                                                                               \
  Network programming Other  Programming of web parsers / scrapers / crawlers
0                 NaN   NaN                                               NaN
1                 NaN   NaN  Programming of web parsers / scrapers / crawlers

                                                                     \
   Software prototyping  Software testing / Writing automated tests
0                   NaN                                         NaN
1  Software prototyping  Software testing / Writing automated tests

                  python.version.upgrade           \
  Web development           ActivePython Anaconda
0             NaN                    NaN      NaN
1             NaN                    NaN      NaN

                                                                          \
   Automatic upgrade via cloud provider Build from source I donâ€™t update
0                                   NaN               NaN            NaN
1  Automatic upgrade via cloud provider               NaN            NaN

                                                         \
  I use Docker containers Intel Distribution for Python
0                     NaN                           NaN
1                     NaN                           NaN

                                                                           \
  OS-provided Python (via apt-get, yum, homebrew, etc_) Other  Python_org
0                                                NaN      NaN  Python_org
1                                                NaN      NaN         NaN

                                                             \
  Somebody else manages Python updates for me pyenv pythonz
0                                         NaN   NaN     NaN
1                                         NaN   NaN     NaN

          run.in.cloud                        \
   In virtual machines None of the following
0                  NaN                   NaN
1  In virtual machines                   NaN

                                                                          \
  On a Platform-as-a-Service (such as Heroku or Google App Engine) Other
0                                                NaN                 NaN
1                                                NaN                 NaN

                                                                         \
  Serverless (such as AWS Lambda or Cloud Functions)  Within containers
0                                                NaN  Within containers
1  Serverless (such as AWS Lambda or Cloud Functi...  Within containers

  unittesting                                                       \
   Hypothesis None Other  Tox doctest  mock nose  pytest  unittest
0         NaN  NaN   NaN  NaN     NaN   NaN  NaN  pytest       NaN
1         NaN  NaN   NaN  NaN     NaN  mock  NaN     NaN  unittest

  web.frameworks                                                          \
          Bottle  CherryPyÂ  Django Falcon FastAPI FlaskÂ   Hug None Other
0            NaN  CherryPyÂ     NaN    NaN     NaN    NaN  NaN  NaN   NaN
1            NaN        NaN    NaN    NaN     NaN    NaN  NaN  NaN   NaN


  PyramidÂ   Tornado web2py
0      NaN      NaN    NaN
1      NaN  Tornado    NaN

## What are the 10 most popular python IDEs?

In [48]:
py_df[('ide', 'main')].dropna().value_counts().head(10)

(ide, main)
VS Code                         8010
PyCharm Professional Edition    5144
PyCharm Community Edition       3815
Vim                             2176
Sublime Text                    1201
Jupyter Notebook                1167
Atom                             784
Other                            711
Emacs                            636
Spyder                           580
Name: count, dtype: int64

## Which 10 other programming languages are most commonly used by Python developers.

In [49]:
py_df['other.lang'].count().sort_values(ascending = False).head(10)

JavaScript      16662
HTML/CSS        15469
Bash / Shell    13793
SQL             13391
C/C++           11623
Java             8109
C#               4460
PHP              4060
TypeScript       3717
Other            3592
dtype: int64

## What are the 10 most common countries from which survey participants came?

In [50]:
# the info is in general whice is a top level index, and country.live 
# whice is a second level index. Then we do our regular job

py_df[('general', 'country.live')].dropna().value_counts(ascending= False).head(10)

(general, country.live)
United States         3975
India                 2800
Germany               1807
China                 1155
United Kingdom        1110
France                1078
Russian Federation     935
Other country          880
Brazil                 812
Canada                 644
Name: count, dtype: int64

## what proportion of python developers have each level of experience?

In [51]:
# i am going to use normalize true to get the percentage

py_df[('general', 'python.years')].value_counts(normalize = True)*100

(general, python.years)
3â€“5 years          28.43
Less than 1 year   23.95
1â€“2 years          22.48
6â€“10 years         15.49
11+ years           9.64
Name: proportion, dtype: float64

## Which country has the greatest number of python developers with 11+ nyears of experience?

In [52]:
py_df['general'][py_df[('general','python.years')] == '11+ years'].groupby('country.live')['python.years'].count().sort_values(ascending = False).head()

country.live
United States     691
Germany           308
United Kingdom    207
France            166
Australia          94
Name: python.years, dtype: int64

## Which country has the greatest proportion of python developers with 11+ years of experience?

In [53]:
country_experience = (py_df['general'][['country.live', 'python.years']])
country_experience.head()

    country.live python.years
0            NaN    3â€“5 years
1          India    3â€“5 years
2  United States    3â€“5 years
3            NaN    11+ years
4          Italy    1â€“2 years

In [54]:
all_per_country = (country_experience['country.live'].value_counts())
all_per_country.head(10)

country.live
United States         3975
India                 2800
Germany               1807
China                 1155
United Kingdom        1110
France                1078
Russian Federation     935
Other country          880
Brazil                 812
Canada                 644
Name: count, dtype: int64

In [55]:
expert_per_country = country_experience.loc[country_experience['python.years'] == '11+ years', 'country.live'].value_counts()
expert_per_country

country.live
United States     691
Germany           308
United Kingdom    207
France            166
Canada             94
                 ...
Pakistan            1
Tunisia             1
Nigeria             1
Ghana               1
Egypt               1
Name: count, Length: 70, dtype: int64

In [56]:
(expert_per_country / all_per_country).sort_values(ascending=False).dropna().head(10)

country.live
Norway           0.27
Ireland          0.23
Australia        0.23
Belgium          0.23
Slovenia         0.22
New Zealand      0.20
Sweden           0.19
Finland          0.19
United Kingdom   0.19
Austria          0.19
Name: count, dtype: float64

Load the Stack Overflow data.

In [57]:
so_df = pd.read_csv('../data/so_2021_survey_results.csv', low_memory= False)
so_df.head()

,ResponseId,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,YearsCodePro,DevType,OrgSize,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSys,NEWStuck,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,NEWOtherComms,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Slovakia,NaN,NaN,"Secondary school (e.g. American high school, G...",18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...,NaN,NaN,"Developer, mobile",20 to 99 employees,EUR European Euro,"4,800.00",Monthly,C++;HTML/CSS;JavaScript;Objective-C;PHP;Swift,Swift,PostgreSQL;SQLite,SQLite,NaN,NaN,Laravel;Symfony,NaN,NaN,NaN,NaN,NaN,PHPStorm;Xcode,Atom;Xcode,MacOS,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow,Multiple times per day,Yes,A few times per month or weekly,"Yes, definitely",No,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,"62,268.00"
1,2,I am a student who is learning to code,"Student, full-time",Netherlands,NaN,NaN,"Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",7,NaN,NaN,NaN,NaN,NaN,NaN,JavaScript;Python,NaN,PostgreSQL,NaN,NaN,NaN,Angular;Flask;Vue.js,NaN,Cordova,NaN,Docker;Git;Yarn,Git,Android Studio;IntelliJ;Notepad++;PyCharm,NaN,Windows,Visit Stack Overflow;Google it,Stack Overflow,Daily or almost daily,Yes,Daily or almost daily,"Yes, definitely",No,18-24 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,NaN
2,3,"I am not primarily a developer, but I write co...","Student, full-time",Russian Federation,NaN,NaN,"Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Assembly;C;Python;R;Rust,Julia;Python;Rust,SQLite,SQLite,Heroku,NaN,Flask,Flask,NumPy;Pandas;TensorFlow;Torch/PyTorch,Keras;NumPy;Pandas;TensorFlow;Torch/PyTorch,NaN,NaN,IPython/Jupyter;PyCharm;RStudio;Sublime Text;V...,IPython/Jupyter;RStudio;Sublime Text;Visual St...,MacOS,Visit Stack Overflow;Google it;Watch help / tu...,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Multiple times per day,"Yes, definitely",Yes,18-24 years old,Man,No,Prefer not to say,Prefer not to say,None of the above,None of the above,Appropriate in length,Easy,NaN
3,4,I am a developer by profession,Employed full-time,Austria,NaN,NaN,"Masterâ€™s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,NaN,NaN,NaN,"Developer, front-end",100 to 499 employees,EUR European Euro,NaN,Monthly,JavaScript;TypeScript,JavaScript;TypeScript,NaN,NaN,NaN,NaN,Angular;jQuery,Angular;jQuery,NaN,NaN,NaN,NaN,NaN,NaN,Windows,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow,Daily or almost daily,Yes,Daily or almost daily,Neutral,No,35-44 years old,Man,No,Straight / Heterosexual,White or of European descent,I am deaf / hard of hearing,NaN,Appropriate in length,Neither easy nor difficult,NaN
4,5,I am a developer by profession,"Independent contractor, freelancer, or self-em...",United Kingdom of Great Britain and Northern I...,NaN,England,"Masterâ€™s degree (M.A., M.S., M.Eng., MBA, etc.)",5 - 10 years,Friend or family member,17,10,"Developer, desktop or enterprise applications;...","Just me - I am a freelancer, sole proprietor, ...",GBP\tPound sterling,NaN,NaN,Bash/Shell;HTML/CSS;Python;SQL,Bash/Shell;HTML/CSS;Python;SQL,Elasticsearch;PostgreSQL;Redis,Cassandra;Elasticsearch;PostgreSQL;Redis,NaN,NaN,Flask,Flask,Apache Spark;Hadoop;NumPy;Pandas,Hadoop;NumPy;Pandas,Docker;Git;Kubernetes;Yarn,Docker;Git;Kubernetes;Yarn,Atom;IPython/Jupyter;Notepad++;PyCharm;Vim,Atom;IPython/Jupyter;Notepad++;PyCharm;Vim;Vis...,Linux-based,Visit Stack Overflow;Go for a walk or other ph...,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,A few times per week,"Yes, somewhat",No,25-34 years old,Man,No,NaN,White or of European descent,None of the above,NaN,Appropriate in length,Easy,NaN

In [58]:
so_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83439 entries, 0 to 83438
Data columns (total 48 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   ResponseId                    83439 non-null  int64
 1   MainBranch                    83439 non-null  object
 2   Employment                    83323 non-null  object
 3   Country                       83439 non-null  object
 4   US_State                      14920 non-null  object
 5   UK_Country                    4418 non-null   object
 6   EdLevel                       83126 non-null  object
 7   Age1stCode                    83243 non-null  object
 8   LearnCode                     82963 non-null  object
 9   YearsCode                     81641 non-null  object
 10  YearsCodePro                  61216 non-null  object
 11  DevType                       66484 non-null  object
 12  OrgSize                       60726 non-null  object
 13  Currency                      61080 non-null  object
 14  CompTotal                     47183 non-null  float64
 15  CompFreq                      52150 non-null  object
 16  LanguageHaveWorkedWith        82357 non-null  object
 17  LanguageWantToWorkWith        76821 non-null  object
 18  DatabaseHaveWorkedWith        69546 non-null  object
 19  DatabaseWantToWorkWith        58299 non-null  object
 20  PlatformHaveWorkedWith        52135 non-null  object
 21  PlatformWantToWorkWith        41619 non-null  object
 22  WebframeHaveWorkedWith        61707 non-null  object
 23  WebframeWantToWorkWith        52095 non-null  object
 24  MiscTechHaveWorkedWith        47055 non-null  object
 25  MiscTechWantToWorkWith        38021 non-null  object
 26  ToolsTechHaveWorkedWith       72537 non-null  object
 27  ToolsTechWantToWorkWith       65480 non-null  object
 28  NEWCollabToolsHaveWorkedWith  81234 non-null  object
 29  NEWCollabToolsWantToWorkWith  73022 non-null  object
 30  OpSys                         83294 non-null  object
 31  NEWStuck                      83052 non-null  object
 32  NEWSOSites                    83171 non-null  object
 33  SOVisitFreq                   82413 non-null  object
 34  SOAccount                     82525 non-null  object
 35  SOPartFreq                    67553 non-null  object
 36  SOComm                        82319 non-null  object
 37  NEWOtherComms                 82828 non-null  object
 38  Age                           82407 non-null  object
 39  Gender                        82286 non-null  object
 40  Trans                         80678 non-null  object
 41  Sexuality                     73366 non-null  object
 42  Ethnicity                     79464 non-null  object
 43  Accessibility                 77603 non-null  object
 44  MentalHealth                  76920 non-null  object
 45  SurveyLength                  81711 non-null  object
 46  SurveyEase                    81948 non-null  object
 47  ConvertedCompYearly           46844 non-null  float64
dtypes: float64(2), int64(1), object(45)
memory usage: 30.6+ MB

## Show the avarage salary for different type of employment

In [59]:
so_df.groupby('Employment')['ConvertedCompYearly'].mean().sort_values(ascending= False)

Employment
I prefer not to say                                    1,455,643.25
Employed full-time                                       121,369.67
Independent contractor, freelancer, or self-employed     107,433.97
Retired                                                   69,533.25
Employed part-time                                        41,136.12
Not employed, and not looking for work                          NaN
Not employed, but looking for work                              NaN
Student, full-time                                              NaN
Student, part-time                                              NaN
Name: ConvertedCompYearly, dtype: float64

In [60]:
# pd.options.display.float_format = '{:,.2f}'.format

In [61]:
so_df.groupby('Employment')['ConvertedCompYearly'].mean().sort_values(ascending= False).dropna()

Employment
I prefer not to say                                    1,455,643.25
Employed full-time                                       121,369.67
Independent contractor, freelancer, or self-employed     107,433.97
Retired                                                   69,533.25
Employed part-time                                        41,136.12
Name: ConvertedCompYearly, dtype: float64

In [62]:
so_df.pivot_table(index='Country',columns='EdLevel', values='ConvertedCompYearly')

EdLevel,"Associate degree (A.A., A.S., etc.)","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)","Masterâ€™s degree (M.A., M.S., M.Eng., MBA, etc.)","Other doctoral degree (Ph.D., Ed.D., etc.)",Primary/elementary school,"Professional degree (JD, MD, etc.)","Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)",Some college/university study without earning a degree,Something else
Country,,,,,,,,,
Afghanistan,NaN,"30,288.00","10,176,704.00",NaN,NaN,NaN,100.00,NaN,NaN
Albania,NaN,"19,152.86","80,127.62",NaN,NaN,"5,298.00","19,890.00","22,884.00","128,522.00"
Algeria,NaN,"21,770.67","15,052.57",NaN,NaN,"12,912.00",NaN,"6,288.00",NaN
Andorra,NaN,"94,045.50","22,056.00","146,981.00",NaN,NaN,NaN,NaN,NaN
Angola,NaN,"31,500.00",NaN,NaN,NaN,NaN,"18,678.00","6,904.00",NaN
...,...,...,...,...,...,...,...,...,...
"Venezuela, Bolivarian Republic of...",NaN,"30,108.77","28,680.00",NaN,"7,200.00","14,833.29","10,200.00","17,720.57",NaN
Viet Nam,"7,827.00","18,463.11","50,599.80","2,592.00","10,479.00","30,000.00",NaN,"18,866.19",NaN
Yemen,NaN,"5,628.67",NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zambia,NaN,"40,173.00","4,908.00",NaN,NaN,NaN,"4,482.00","12,105.33","8,184.00"
Zimbabwe,"36,000.00","8,399.27",NaN,NaN,NaN,NaN,NaN,"20,000.00",NaN

## Ceate this pivot table again, only including countries in the OECD subset

In [63]:
oecd_df = pd.read_csv('../data/oecd_locations.csv', 
                      header=None, 
                      index_col=1,
                      names=['abbrev', 'Country'])
oecd_df.head()

          abbrev
Country
Australia    AUS
Austria      AUT
Belgium      BEL
Canada       CAN
Denmark      DNK

In [64]:
oecd_df.join(so_df.set_index('Country')).pivot_table(index='Country',columns='EdLevel', values='ConvertedCompYearly')

EdLevel,"Associate degree (A.A., A.S., etc.)","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)","Masterâ€™s degree (M.A., M.S., M.Eng., MBA, etc.)","Other doctoral degree (Ph.D., Ed.D., etc.)",Primary/elementary school,"Professional degree (JD, MD, etc.)","Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)",Some college/university study without earning a degree,Something else
Country,,,,,,,,,
Australia,"117,049.64","180,794.16","106,794.32","150,234.96","153,327.50","108,725.00","158,931.28","127,063.53","231,987.17"
Austria,"43,623.38","66,096.13","77,645.66","74,783.17","86,877.00","38,915.33","47,438.83","53,906.05","45,772.53"
Belgium,"35,664.00","68,474.70","88,580.41","80,832.44","11,342,349.25","71,000.20","43,224.13","88,006.29","27,035.50"
Brazil,"25,347.42","47,681.23","42,056.01","43,123.21","7,880.00","25,449.67","15,072.89","39,978.02","20,288.71"
Canada,"87,930.35","140,668.24","144,733.35","102,989.35","73,787.83","82,953.40","180,584.81","155,090.08","60,795.17"
Denmark,"80,217.33","80,430.94","115,751.85","102,785.19","91,056.57","114,144.89","90,411.74","85,131.35","95,479.86"
Finland,"282,353.67","69,381.34","74,360.98","61,508.25","77,832.00","83,016.00","59,424.32","89,255.56","35,024.00"
France,"54,394.89","65,062.38","94,585.73","140,402.86","34,181.00","78,342.27","53,981.81","55,119.45","42,884.04"
Germany,"98,530.52","102,751.23","110,611.98","108,718.46","74,943.67","97,330.14","82,865.84","95,737.77","109,333.99"
Hungary,"51,041.00","48,756.45","46,771.71","52,833.60","48,100.00","9,852.00","33,440.80","37,102.89","28,911.00"
Israel,"146,420.90","124,973.40","128,492.71","131,812.62","100,514.57","132,336.00","97,938.78","130,049.04","96,142.50"
Italy,"36,427.94","73,697.22","79,132.19","93,490.78","525,992.17","117,121.37","75,114.40","81,531.72","32,690.22"
Japan,"143,196.83","85,821.47","130,143.19","157,239.40","44,965.00",NaN,"57,916.40","91,163.04","194,514.00"

In [65]:
(
    oecd_df
    .join(so_df.set_index('Country'))
    .pivot_table(index='Country',
                 columns='EdLevel',
                 values='ConvertedCompYearly')
    ['Associate degree (A.A., A.S., etc.)']
    .sort_values(ascending=False) 
)

Country
Finland     282,353.67
Israel      146,420.90
Japan       143,196.83
Australia   117,049.64
Germany      98,530.52
Canada       87,930.35
Denmark      80,217.33
France       54,394.89
Hungary      51,041.00
Austria      43,623.38
Italy        36,427.94
Belgium      35,664.00
Brazil       25,347.42
Name: Associate degree (A.A., A.S., etc.), dtype: float64

In [66]:
(
    oecd_df
    .join(so_df.set_index('Country'))
    .pivot_table(index='Country',
                 columns='EdLevel',
                 values='ConvertedCompYearly')
    ['Other doctoral degree (Ph.D., Ed.D., etc.)']
    .sort_values(ascending=False) 
)

Country
Japan       157,239.40
Australia   150,234.96
France      140,402.86
Israel      131,812.62
Germany     108,718.46
Canada      102,989.35
Denmark     102,785.19
Italy        93,490.78
Belgium      80,832.44
Austria      74,783.17
Finland      61,508.25
Hungary      52,833.60
Brazil       43,123.21
Name: Other doctoral degree (Ph.D., Ed.D., etc.), dtype: float64

## Remove rows from so_df in which LanguageHaveWorkedWith  is NaN

In [67]:
so_df = so_df.dropna(subset=['LanguageHaveWorkedWith'])

## Remove rows from so_df in whice python isn't in LanguageHaveWorkedWith

In [68]:
so_df = so_df.loc[so_df['LanguageHaveWorkedWith'].str.contains('Python')]

## Remove rows from so_df in whice YearsCode NaN

In [71]:
so_df = so_df.dropna(subset= 'YearsCode')

## In YeaesCode, replace "Less than 1 year" with 0 and "More then 50 years" with 51

In [73]:
so_df.loc[so_df['YearsCode'] == "More than 50 years", 'YearsCode'] = 51
so_df.loc[so_df['YearsCode'] == "Less than 1 year", 'YearsCode'] = 0

In [75]:
so_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 38997 entries, 1 to 83437
Data columns (total 48 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   ResponseId                    38997 non-null  int64
 1   MainBranch                    38997 non-null  object
 2   Employment                    38956 non-null  object
 3   Country                       38997 non-null  object
 4   US_State                      7666 non-null   object
 5   UK_Country                    2096 non-null   object
 6   EdLevel                       38921 non-null  object
 7   Age1stCode                    38972 non-null  object
 8   LearnCode                     38905 non-null  object
 9   YearsCode                     38997 non-null  object
 10  YearsCodePro                  25916 non-null  object
 11  DevType                       28212 non-null  object
 12  OrgSize                       25413 non-null  object
 13  Currency                      25506 non-null  object
 14  CompTotal                     19922 non-null  float64
 15  CompFreq                      21767 non-null  object
 16  LanguageHaveWorkedWith        38997 non-null  object
 17  LanguageWantToWorkWith        36650 non-null  object
 18  DatabaseHaveWorkedWith        32322 non-null  object
 19  DatabaseWantToWorkWith        26931 non-null  object
 20  PlatformHaveWorkedWith        25073 non-null  object
 21  PlatformWantToWorkWith        19991 non-null  object
 22  WebframeHaveWorkedWith        28309 non-null  object
 23  WebframeWantToWorkWith        23481 non-null  object
 24  MiscTechHaveWorkedWith        26272 non-null  object
 25  MiscTechWantToWorkWith        21357 non-null  object
 26  ToolsTechHaveWorkedWith       35048 non-null  object
 27  ToolsTechWantToWorkWith       31806 non-null  object
 28  NEWCollabToolsHaveWorkedWith  38465 non-null  object
 29  NEWCollabToolsWantToWorkWith  34725 non-null  object
 30  OpSys                         38975 non-null  object
 31  NEWStuck                      38907 non-null  object
 32  NEWSOSites                    38936 non-null  object
 33  SOVisitFreq                   38718 non-null  object
 34  SOAccount                     38754 non-null  object
 35  SOPartFreq                    31716 non-null  object
 36  SOComm                        38697 non-null  object
 37  NEWOtherComms                 38785 non-null  object
 38  Age                           38584 non-null  object
 39  Gender                        38506 non-null  object
 40  Trans                         37924 non-null  object
 41  Sexuality                     34586 non-null  object
 42  Ethnicity                     37356 non-null  object
 43  Accessibility                 36623 non-null  object
 44  MentalHealth                  36327 non-null  object
 45  SurveyLength                  38380 non-null  object
 46  SurveyEase                    38507 non-null  object
 47  ConvertedCompYearly           19787 non-null  float64
dtypes: float64(2), int64(1), object(45)
memory usage: 14.6+ MB

In [77]:
# turning YearsCode column into integer from object
so_df['YearsCode'] = so_df['YearsCode'].astype(np.int16)

## Creat a new column called "EXPERIENCE" in so_df, categorizing values in YearsCode

In [79]:
so_df['experience'] = pd.cut(so_df['YearsCode'], 
                             bins=[-1, 1, 2, 5, 10, 100], 
                             labels=['Less than 1 year',
                             '1-2 years',
                             '3-5 years',
                             '6-10 years',
                             '11+ years'])

so_df.head()

,ResponseId,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,YearsCodePro,DevType,OrgSize,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSys,NEWStuck,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,NEWOtherComms,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly,experience
1,2,I am a student who is learning to code,"Student, full-time",Netherlands,NaN,NaN,"Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",7,NaN,NaN,NaN,NaN,NaN,NaN,JavaScript;Python,NaN,PostgreSQL,NaN,NaN,NaN,Angular;Flask;Vue.js,NaN,Cordova,NaN,Docker;Git;Yarn,Git,Android Studio;IntelliJ;Notepad++;PyCharm,NaN,Windows,Visit Stack Overflow;Google it,Stack Overflow,Daily or almost daily,Yes,Daily or almost daily,"Yes, definitely",No,18-24 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,NaN,6-10 years
4,5,I am a developer by profession,"Independent contractor, freelancer, or self-em...",United Kingdom of Great Britain and Northern I...,NaN,England,"Masterâ€™s degree (M.A., M.S., M.Eng., MBA, etc.)",5 - 10 years,Friend or family member,17,10,"Developer, desktop or enterprise applications;...","Just me - I am a freelancer, sole proprietor, ...",GBP\tPound sterling,NaN,NaN,Bash/Shell;HTML/CSS;Python;SQL,Bash/Shell;HTML/CSS;Python;SQL,Elasticsearch;PostgreSQL;Redis,Cassandra;Elasticsearch;PostgreSQL;Redis,NaN,NaN,Flask,Flask,Apache Spark;Hadoop;NumPy;Pandas,Hadoop;NumPy;Pandas,Docker;Git;Kubernetes;Yarn,Docker;Git;Kubernetes;Yarn,Atom;IPython/Jupyter;Notepad++;PyCharm;Vim,Atom;IPython/Jupyter;Notepad++;PyCharm;Vim;Vis...,Linux-based,Visit Stack Overflow;Go for a walk or other ph...,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,A few times per week,"Yes, somewhat",No,25-34 years old,Man,No,NaN,White or of European descent,None of the above,NaN,Appropriate in length,Easy,NaN,11+ years
9,10,I am a developer by profession,Employed full-time,Sweden,NaN,NaN,"Masterâ€™s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,School,7,4,Data scientist or machine learning specialist,10 to 19 employees,SEK\tSwedish krona,"42,000.00",Monthly,C++;Python,Haskell;Python,PostgreSQL,NaN,NaN,NaN,NaN,NaN,Keras;NumPy;Pandas;TensorFlow;Torch/PyTorch,Keras;NumPy;TensorFlow;Torch/PyTorch,Git,Git,IPython/Jupyter;Vim;Visual Studio Code,Emacs;IPython/Jupyter;Vim;Visual Studio Code,Linux-based,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Daily or almost daily,"Yes, somewhat",No,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,"51,552.00",6-10 years
13,14,I am a student who is learning to code,Employed full-time,Peru,NaN,NaN,"Masterâ€™s degree (M.A., M.S., M.Eng., MBA, etc.)",5 - 10 years,School,10,NaN,Data scientist or machine learning specialist,NaN,NaN,NaN,NaN,C;C++;JavaScript;Python;R;SQL,NaN,MySQL;PostgreSQL,NaN,AWS,DigitalOcean,Flask,Vue.js,Apache Spark;Pandas;TensorFlow,NaN,Docker;Git,NaN,Atom;RStudio,NaN,MacOS,Visit Stack Overflow;Go for a walk or other ph...,Stack Overflow,Daily or almost daily,Yes,A few times per week,Neutral,No,Prefer not to say,Prefer not to say,Prefer not to say,Prefer not to say,Prefer not to say,Prefer not to say,Prefer not to say,Too long,Neither easy nor difficult,NaN,6-10 years
15,16,I am a student who is learning to code,"Student, full-time",United States of America,Missouri,NaN,"Secondary school (e.g. American high school, G...",5 - 10 years,Other (please specify):,7,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell;Python,Bash/Shell;Python,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Git,Git,Emacs;Neovim;Vim,Neovim;Vim,Linux-based,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Less than once per month or monthly,Neutral,No,Under 18 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,I have a concentration and/or memory disorder ...,Too long,Easy,NaN,6-10 years

In [ ]:
# BD_df = so_df[so_df['Country'] == "Bangladesh"].sort_values('YearsCode', ascending=False)
# BD_df.to_csv('bd_experienced.csv',sep=",")

## According to the stack overflow survey, what proportion of python developers have each level of experience?

In [90]:
so_df['experience'].value_counts()

experience
11+ years           14561
6-10 years          12424
3-5 years            8678
1-2 years            1850
Less than 1 year     1484
Name: count, dtype: int64